export const USER_LOGIN = 'USER_LOGIN'
export const USER_CREATE = 'USER_CREATE'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_READ = 'USER_READ'

export const CRON_UPDATE = 'CRON_UPDATE'

export const QUERY_DELETE = 'QUERY_DELETE'
export const QUERY_CREATE = 'QUERY_CREATE'

export const BLACKLIST_ITEM_DELETE = 'BLACKLIST_ITEM_DELETE'
export const BLACKLIST_ITEM_CREATE = 'BLACKLIST_ITEM_CREATE'

export const ACCOUNT_DELETE = 'ACCOUNT_DELETE'
